import type { Blueprint } from "../types/index.js";

export function loadBlueprintLibrary(): Blueprint[] {
  return [
    {
      id: "BP-SALES-01", name: "Automated Lead Qualification", department: "Sales",
      description: "Auto-enrich, score, and route inbound leads using AI research and ICP matching.",
      typicalTriggers: ["Manual lead research", "No lead scoring", "Inconsistent routing"],
      prerequisites: ["CRM access", "Defined ICP criteria"],
      requiredCapabilities: ["Lead enrichment data", "CRM API"],
      exclusions: ["No CRM", "Under 5 SDRs"],
      aiComponents: ["Lead enrichment", "Scoring model", "Routing rules"],
      evidenceTags: ["lead_qualification", "sales_efficiency"],
      effort: "3-4 weeks", timeToValue: "4-6 weeks",
    },
    {
      id: "BP-SALES-02", name: "Sales Forecasting Intelligence", department: "Sales",
      description: "AI-powered pipeline analysis and revenue forecasting with scenario modeling.",
      typicalTriggers: ["Inaccurate forecasts", "Manual pipeline review", "Missed targets"],
      prerequisites: ["CRM with pipeline data", "6+ months historical data"],
      requiredCapabilities: ["Pipeline analytics", "Historical data"],
      exclusions: ["Under $1M ARR", "No CRM"],
      aiComponents: ["Forecast model", "Scenario simulation", "Risk flags"],
      evidenceTags: ["forecasting", "sales_analytics"],
      effort: "4-6 weeks", timeToValue: "2-3 months",
    },
    {
      id: "BP-SALES-03", name: "Account-Based Experience Orchestration", department: "Sales",
      description: "Orchestrate multi-channel ABX campaigns with AI-personalized content sequencing.",
      typicalTriggers: ["Low enterprise conversion", "Generic outreach", "Long sales cycles"],
      prerequisites: ["ABM platform or CRM", "Content library", "Multi-channel tools"],
      requiredCapabilities: ["Multi-channel orchestration", "Content personalization"],
      exclusions: ["No enterprise deals", "Under 10 target accounts"],
      aiComponents: ["Content personalization", "Channel sequencing", "Engagement scoring"],
      evidenceTags: ["abm", "sales_outreach"],
      effort: "6-8 weeks", timeToValue: "3-4 months",
    },
    {
      id: "BP-SALES-04", name: "Conversational Sales Assistant", department: "Sales",
      description: "AI-powered sales assistant for objection handling, discovery questions, and next-best-action recommendations.",
      typicalTriggers: ["Inconsistent discovery", "Long ramp for new AEs", "Missed cross-sell"],
      prerequisites: ["CRM integration", "Sales playbook"],
      requiredCapabilities: ["Conversation AI", "CRM data"],
      exclusions: ["Under 5 AEs", "No structured sales process"],
      aiComponents: ["Conversation AI", "Next-best-action", "Discovery guidance"],
      evidenceTags: ["sales_enablement", "sales_efficiency"],
      effort: "4-6 weeks", timeToValue: "6-8 weeks",
    },
    {
      id: "BP-MKTG-01", name: "Intent-Based Lead Scoring", department: "Marketing",
      description: "Score leads using intent signals from content consumption, engagement, and firmographic data.",
      typicalTriggers: ["Low lead conversion", "Manual lead scoring", "Marketing-sales misalignment"],
      prerequisites: ["Marketing automation", "Lead capture forms", "Website analytics"],
      requiredCapabilities: ["Intent data source", "Marketing automation API"],
      exclusions: ["Under 500 leads/month", "No website traffic data"],
      aiComponents: ["Intent scoring", "Predictive lead model"],
      evidenceTags: ["lead_scoring", "marketing_automation"],
      effort: "3-4 weeks", timeToValue: "4-6 weeks",
    },
    {
      id: "BP-MKTG-02", name: "Personalized Campaign Generator", department: "Marketing",
      description: "AI generates personalized email and ad campaigns based on segment behavior and preferences.",
      typicalTriggers: ["Generic campaigns", "Low email engagement", "High unsubscribe rate"],
      prerequisites: ["Email platform", "Customer segments", "Content library"],
      requiredCapabilities: ["Email API", "Segmentation data"],
      exclusions: ["Under 1K contacts", "No customer data platform"],
      aiComponents: ["Content generation", "Segment analysis", "A/B optimization"],
      evidenceTags: ["campaign_personalization", "marketing_automation"],
      effort: "4-6 weeks", timeToValue: "6-8 weeks",
    },
    {
      id: "BP-MKTG-03", name: "Content Intelligence Platform", department: "Marketing",
      description: "AI analyzes content performance, identifies gaps, and recommends topics and formats.",
      typicalTriggers: ["Low content engagement", "Unknown content ROI", "Topic ideation struggles"],
      prerequisites: ["Content management system", "Analytics tools"],
      requiredCapabilities: ["Content analytics", "SEO data"],
      exclusions: ["No content team", "Under 10 pieces/month"],
      aiComponents: ["Content analysis", "Topic modeling", "Performance prediction"],
      evidenceTags: ["content_intelligence", "marketing_analytics"],
      effort: "4-6 weeks", timeToValue: "2-3 months",
    },
    {
      id: "BP-CS-01", name: "Proactive Health Scoring", department: "Customer Success",
      description: "Automated health scores using product usage, support history, and billing signals to flag at-risk accounts.",
      typicalTriggers: ["Reactive CS approach", "Unknown account health", "High churn"],
      prerequisites: ["Product analytics data", "CS platform", "Billing data"],
      requiredCapabilities: ["Usage data pipeline", "CS tool API"],
      exclusions: ["No product analytics", "Under 50 accounts"],
      aiComponents: ["Health score model", "Churn prediction", "Alert triggers"],
      evidenceTags: ["health_scoring", "cs_efficiency"],
      effort: "4-5 weeks", timeToValue: "6-8 weeks",
    },
    {
      id: "BP-CS-02", name: "Automated Onboarding Sequences", department: "Customer Success",
      description: "AI-personalized onboarding flows that adapt to user role, product area, and engagement patterns.",
      typicalTriggers: ["Long time-to-value", "Inconsistent onboarding", "High early churn"],
      prerequisites: ["Product analytics", "Email/messaging platform"],
      requiredCapabilities: ["User segmentation", "Multi-channel messaging"],
      exclusions: ["Under 100 new users/month", "No product analytics"],
      aiComponents: ["Sequence personalization", "Engagement timing", "Content recommendation"],
      evidenceTags: ["onboarding", "cs_efficiency"],
      effort: "3-5 weeks", timeToValue: "4-6 weeks",
    },
    {
      id: "BP-CS-03", name: "Customer Lifecycle AI", department: "Customer Success",
      description: "End-to-end customer lifecycle management with AI-driven touch-point recommendations and QBR automation.",
      typicalTriggers: ["No structured lifecycle", "Manual QBR prep", "Inconsistent touchpoints"],
      prerequisites: ["CRM/CS platform", "Product usage data", "Customer segments"],
      requiredCapabilities: ["Lifecycle analytics", "Automated reporting"],
      exclusions: ["Under 200 accounts", "No CS team dedicated"],
      aiComponents: ["Lifecycle stage detection", "Touchpoint recommendations", "QBR generator"],
      evidenceTags: ["lifecycle_management", "cs_efficiency"],
      effort: "6-8 weeks", timeToValue: "3-4 months",
    },
    {
      id: "BP-SUPP-01", name: "Self-Service Support Resolution", department: "Support",
      description: "AI chatbot with knowledge base integration for automated Tier-1 ticket resolution.",
      typicalTriggers: ["High ticket volume", "Repetitive Tier-1 issues", "Slow first response"],
      prerequisites: ["Knowledge base", "Ticketing system API"],
      requiredCapabilities: ["Knowledge base content", "Ticketing integration"],
      exclusions: ["Under 500 tickets/month", "No KB content"],
      aiComponents: ["Intent recognition", "KB retrieval", "Ticket deflection"],
      evidenceTags: ["ticket_routing", "support_efficiency"],
      effort: "4-6 weeks", timeToValue: "6-8 weeks",
    },
    {
      id: "BP-SUPP-02", name: "Smart Ticket Triage & Routing", department: "Support",
      description: "AI classifies, prioritizes, and routes tickets to the right team or agent based on intent and urgency.",
      typicalTriggers: ["Misrouted tickets", "Inconsistent prioritization", "Agent overload"],
      prerequisites: ["Ticketing system API", "Team structure defined"],
      requiredCapabilities: ["Ticket classification", "Routing rules engine"],
      exclusions: ["Under 3 support agents", "No ticket categories"],
      aiComponents: ["Intent classification", "Priority scoring", "Skills-based routing"],
      evidenceTags: ["ticket_routing", "support_efficiency"],
      effort: "3-4 weeks", timeToValue: "4-6 weeks",
    },
    {
      id: "BP-SUPP-03", name: "Support Quality Assurance AI", department: "Support",
      description: "Automated QA of support conversations with sentiment analysis, coverage scoring, and coaching recommendations.",
      typicalTriggers: ["Inconsistent QA", "Unknown agent performance", "No coaching data"],
      prerequisites: ["Ticket/chat data access", "QA criteria defined"],
      requiredCapabilities: ["Conversation data", "QA rubric"],
      exclusions: ["Under 5 agents", "No conversation data archived"],
      aiComponents: ["Sentiment analysis", "Coverage scoring", "Coaching recommendation"],
      evidenceTags: ["support_quality", "support_analytics"],
      effort: "4-6 weeks", timeToValue: "2-3 months",
    },
    {
      id: "BP-SUPP-04", name: "Agent Assist & Knowledge Retrieval", department: "Support",
      description: "Real-time AI suggestions for support agents: relevant KB articles, similar cases, and response drafts.",
      typicalTriggers: ["Long handle times", "Inconsistent answers", "New agent ramp issues"],
      prerequisites: ["Knowledge base", "Live chat/ticketing system"],
      requiredCapabilities: ["Real-time context access", "KB search"],
      exclusions: ["Under 1K tickets/month", "No KB"],
      aiComponents: ["Context retrieval", "Response suggestion", "Similar case lookup"],
      evidenceTags: ["agent_assist", "support_efficiency"],
      effort: "5-7 weeks", timeToValue: "6-10 weeks",
    },
    {
      id: "BP-FIN-01", name: "Automated Invoice Processing", department: "Finance",
      description: "AI extracts invoice data, matches to POs, routes for approval, and syncs to ERP.",
      typicalTriggers: ["Manual invoice entry", "Slow AP cycle", "PO matching errors"],
      prerequisites: ["ERP/accounting system", "Invoice source (email/portal)"],
      requiredCapabilities: ["Document processing AI", "ERP API"],
      exclusions: ["Under 200 invoices/month", "No ERP system"],
      aiComponents: ["Document extraction", "PO matching", "Approval routing"],
      evidenceTags: ["invoice_processing", "finance_automation"],
      effort: "4-6 weeks", timeToValue: "6-8 weeks",
    },
    {
      id: "BP-FIN-02", name: "Expense Management Automation", department: "Finance",
      description: "AI-powered expense categorization, policy compliance checking, and approval workflow automation.",
      typicalTriggers: ["Manual expense reports", "Policy violations missed", "Slow reimbursements"],
      prerequisites: ["Expense policy defined", "Accounting system"],
      requiredCapabilities: ["Receipt OCR", "Policy rules engine"],
      exclusions: ["Under 50 employees", "No formal expense policy"],
      aiComponents: ["Receipt analysis", "Policy checking", "Categorization"],
      evidenceTags: ["expense_management", "finance_automation"],
      effort: "3-5 weeks", timeToValue: "4-6 weeks",
    },
    {
      id: "BP-FIN-03", name: "Financial Forecasting & Planning", department: "Finance",
      description: "AI-driven financial modeling with scenario analysis, variance detection, and rolling forecasts.",
      typicalTriggers: ["Slow month-end close", "Inaccurate forecasts", "Manual consolidation"],
      prerequisites: ["Historical financial data", "FP&A tool or spreadsheet process"],
      requiredCapabilities: ["Financial data warehouse", "Reporting tools"],
      exclusions: ["Under $5M ARR", "No dedicated finance team"],
      aiComponents: ["Forecast model", "Variance analysis", "Scenario simulation"],
      evidenceTags: ["forecasting", "finance_analytics"],
      effort: "6-10 weeks", timeToValue: "3-4 months",
    },
    {
      id: "BP-FIN-04", name: "Automated Revenue Recognition", department: "Finance",
      description: "AI automates ASC 606 revenue recognition with contract analysis and deferred revenue schedules.",
      typicalTriggers: ["Complex revenue rules", "Manual deferred revenue", "Audit concerns"],
      prerequisites: ["Billing system", "Contract repository", "Accounting system"],
      requiredCapabilities: ["Contract analysis AI", "Revenue rules engine"],
      exclusions: ["Under $10M ARR", "Simple subscription only"],
      aiComponents: ["Contract analysis", "Revenue schedule automation", "ASC 606 compliance"],
      evidenceTags: ["revenue_recognition", "finance_compliance"],
      effort: "8-12 weeks", timeToValue: "4-6 months",
    },
    {
      id: "BP-PROD-01", name: "Product Intelligence & Analytics", department: "Product",
      description: "AI-powered product analytics with automated insights, feature adoption tracking, and roadmap recommendations.",
      typicalTriggers: ["No product analytics", "Data-informed not data-driven", "Feature discovery"],
      prerequisites: ["Product analytics tool", "Event tracking implemented"],
      requiredCapabilities: ["Product data pipeline", "Analytics platform"],
      exclusions: ["No product analytics tool", "Under 1K MAU"],
      aiComponents: ["Insight generation", "Adoption analysis", "Roadmap suggestions"],
      evidenceTags: ["product_analytics", "product_intelligence"],
      effort: "4-6 weeks", timeToValue: "6-8 weeks",
    },
    {
      id: "BP-PROD-02", name: "User Research Synthesis", department: "Product",
      description: "AI aggregates and synthesizes user research across interviews, surveys, and support data into actionable themes.",
      typicalTriggers: ["Unstructured user feedback", "Missed user needs", "Research silos"],
      prerequisites: ["User research repository", "Feedback collection tools"],
      requiredCapabilities: ["Research data aggregation", "Theme extraction"],
      exclusions: ["No dedicated product team", "Under 5 user interviews/month"],
      aiComponents: ["Theme extraction", "Sentiment analysis", "Gap identification"],
      evidenceTags: ["user_research", "product_intelligence"],
      effort: "3-5 weeks", timeToValue: "4-6 weeks",
    },
    {
      id: "BP-ENGR-01", name: "Engineering Documentation AI", department: "Engineering",
      description: "Auto-generated code documentation, PR context summaries, and searchable knowledge base.",
      typicalTriggers: ["Poor documentation", "Long PR reviews", "Knowledge silos"],
      prerequisites: ["Code repository (GitHub/GitLab)", "CI/CD pipeline"],
      requiredCapabilities: ["Source code access", "PR review system"],
      exclusions: ["Under 5 engineers", "No CI/CD pipeline"],
      aiComponents: ["Doc generation", "PR context summarization", "Knowledge base indexing"],
      evidenceTags: ["documentation", "engineering_efficiency"],
      effort: "4-6 weeks", timeToValue: "6-8 weeks",
    },
    {
      id: "BP-ENGR-02", name: "Code Review Intelligence", department: "Engineering",
      description: "AI-assisted code review with vulnerability detection, best-practice suggestions, and context-aware comments.",
      typicalTriggers: ["Inconsistent code quality", "Security concerns", "Long review cycles"],
      prerequisites: ["Code repository", "Test suite", "Code standards documented"],
      requiredCapabilities: ["Static analysis pipeline", "Code review platform"],
      exclusions: ["Under 3 engineers", "No test suite"],
      aiComponents: ["Code analysis", "Vulnerability detection", "Review suggestions"],
      evidenceTags: ["code_review", "engineering_quality"],
      effort: "6-8 weeks", timeToValue: "2-3 months",
    },
    {
      id: "BP-ENGR-03", name: "Incident Response Automation", department: "Engineering",
      description: "AI-powered incident detection, diagnosis, and response with automated runbooks.",
      typicalTriggers: ["Manual incident response", "Long MTTR", "Inconsistent runbooks"],
      prerequisites: ["Monitoring/observability stack", "Incident management tool"],
      requiredCapabilities: ["Monitoring API", "Incident management integration"],
      exclusions: ["Under 5 engineers", "No monitoring system"],
      aiComponents: ["Anomaly detection", "Root cause analysis", "Runbook automation"],
      evidenceTags: ["incident_response", "engineering_reliability"],
      effort: "6-10 weeks", timeToValue: "2-4 months",
    },
    {
      id: "BP-HR-01", name: "HR Service Desk Automation", department: "People/HR",
      description: "AI chatbot for HR inquiries, leave management, policy lookups, and onboarding task automation.",
      typicalTriggers: ["HR team overwhelmed with questions", "Manual onboarding", "Policy confusion"],
      prerequisites: ["HRIS system", "HR policy documentation"],
      requiredCapabilities: ["HRIS API", "Policy content"],
      exclusions: ["Under 50 employees", "No HRIS"],
      aiComponents: ["HR Q&A chatbot", "Onboarding workflow", "Policy retrieval"],
      evidenceTags: ["hr_automation", "people_operations"],
      effort: "4-6 weeks", timeToValue: "6-8 weeks",
    },
    {
      id: "BP-HR-02", name: "Performance Review Intelligence", department: "People/HR",
      description: "AI-assisted performance reviews with feedback aggregation, bias detection, and development recommendations.",
      typicalTriggers: ["Inconsistent reviews", "Recency bias", "No development plans"],
      prerequisites: ["HRIS with review data", "Feedback collection process"],
      requiredCapabilities: ["Review data access", "Feedback aggregation"],
      exclusions: ["Under 30 employees", "No formal review process"],
      aiComponents: ["Feedback aggregation", "Bias detection", "Development suggestions"],
      evidenceTags: ["performance_reviews", "people_analytics"],
      effort: "5-8 weeks", timeToValue: "3-4 months",
    },
    {
      id: "BP-HR-03", name: "Talent Acquisition Intelligence", department: "People/HR",
      description: "AI-powered candidate sourcing, screening, and matching with automated interview scheduling.",
      typicalTriggers: ["Slow hiring", "High screening burden", "Candidate drop-off"],
      prerequisites: ["ATS system", "Job descriptions", "Interview process defined"],
      requiredCapabilities: ["ATS API", "Candidate sourcing channels"],
      exclusions: ["Under 20 hires/year", "No ATS"],
      aiComponents: ["Candidate matching", "Resume screening", "Scheduling automation"],
      evidenceTags: ["talent_acquisition", "people_operations"],
      effort: "6-8 weeks", timeToValue: "2-3 months",
    },
    {
      id: "BP-LEGAL-01", name: "Contract Review & Analysis", department: "Legal",
      description: "AI extracts clauses, flags risky terms, and auto-populates standard contract templates.",
      typicalTriggers: ["Manual contract review", "Legal bottlenecks", "Missed risky terms"],
      prerequisites: ["Contract library", "CLM or document storage"],
      requiredCapabilities: ["Document AI", "Clause library"],
      exclusions: ["Under 50 contracts/year", "No standard contract templates"],
      aiComponents: ["Clause extraction", "Risk flagging", "Template population"],
      evidenceTags: ["contract_review", "legal_efficiency"],
      effort: "6-10 weeks", timeToValue: "3-4 months",
    },
    {
      id: "BP-LEGAL-02", name: "Compliance Monitoring AI", department: "Legal",
      description: "Continuous monitoring of regulatory changes, automated impact assessment, and compliance document updates.",
      typicalTriggers: ["Compliance concerns", "Manual regulatory tracking", "Audit preparation burden"],
      prerequisites: ["Regulatory framework mapped", "Compliance documentation"],
      requiredCapabilities: ["Regulatory data sources", "Document management"],
      exclusions: ["No formal compliance program", "Under 50 employees"],
      aiComponents: ["Regulatory change detection", "Impact analysis", "Document updates"],
      evidenceTags: ["compliance_monitoring", "legal_risk"],
      effort: "8-12 weeks", timeToValue: "4-6 months",
    },
    {
      id: "BP-LEGAL-03", name: "Legal Research & Briefing", department: "Legal",
      description: "AI-assisted legal research with case summarization, precedent identification, and brief drafting.",
      typicalTriggers: ["Time-consuming research", "Inconsistent brief quality", "Missed precedents"],
      prerequisites: ["Legal research database access", "Matter management system"],
      requiredCapabilities: ["Legal database API", "Document generation"],
      exclusions: ["In-house legal team under 3", "No legal research budget"],
      aiComponents: ["Case summarization", "Precedent search", "Brief drafting"],
      evidenceTags: ["legal_research", "legal_efficiency"],
      effort: "6-10 weeks", timeToValue: "3-5 months",
    },
    {
      id: "BP-OPS-01", name: "Operational Process Automation", department: "Operations",
      description: "End-to-end automation of recurring operational workflows with AI-driven exception handling.",
      typicalTriggers: ["Manual recurring processes", "Cross-dept coordination burden", "Process inconsistencies"],
      prerequisites: ["Process documentation", "System access", "Stakeholder buy-in"],
      requiredCapabilities: ["Process mapping", "API integrations", "Workflow engine"],
      exclusions: ["Under 50 employees", "No documented processes"],
      aiComponents: ["Process analysis", "Exception handling", "Workflow orchestration"],
      evidenceTags: ["process_automation", "operations_efficiency"],
      effort: "8-12 weeks", timeToValue: "3-5 months",
    },
    {
      id: "BP-OPS-02", name: "Business Intelligence Automation", department: "Operations",
      description: "AI-powered reporting with automated data consolidation, anomaly detection, and executive summaries.",
      typicalTriggers: ["Manual report building", "Data scattered across sources", "Delayed insights"],
      prerequisites: ["Data warehouse or BI tool", "Key data sources accessible"],
      requiredCapabilities: ["Data pipeline", "BI platform API"],
      exclusions: ["No data warehouse", "Under 5 data sources"],
      aiComponents: ["Data consolidation", "Anomaly detection", "Narrative generation"],
      evidenceTags: ["bi_automation", "operations_analytics"],
      effort: "6-8 weeks", timeToValue: "2-3 months",
    },
    {
      id: "BP-OPS-03", name: "Vendor Management Intelligence", department: "Operations",
      description: "AI-driven vendor evaluation, contract comparison, and performance monitoring across the vendor portfolio.",
      typicalTriggers: ["Spreadsheet vendor tracking", "Unknown vendor performance", "Contract renewal surprises"],
      prerequisites: ["Vendor list", "Contract repository", "Spend data"],
      requiredCapabilities: ["Vendor data aggregation", "Contract analysis"],
      exclusions: ["Under 10 vendors", "No procurement function"],
      aiComponents: ["Vendor evaluation", "Performance monitoring", "Risk scoring"],
      evidenceTags: ["vendor_management", "operations_efficiency"],
      effort: "5-8 weeks", timeToValue: "2-4 months",
    },
  ];
}
